name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present -- --base /lovable-milk-manager/

      - name: Prepare SPA fallback and favicon
        run: |
          # copy index for SPA client-side routing fallback
          cp dist/index.html dist/404.html
          # if we have a base64 favicon, decode it to dist
          if [ -f public/favicon.base64 ]; then
            base64 -d public/favicon.base64 > dist/favicon.png || true
          fi

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          keep_files: false
